<template><div v-permission="'observability:dashboard:read'"><PanelState v-if="loadError" state="error" :message="loadError"/><component :is="componentFor(panel.panel_type)" v-for="panel in dashboard?.panels" v-else :key="panel.id" :result="results.get(panel.id)?.result" :state="panelState(panel.id)" :message="errors.get(panel.id)" :unit="panel.unit"/></div></template>
<script setup lang="ts">
import{inject,onBeforeUnmount,onMounted,ref}from'vue';import{useRoute}from'vue-router';import{useI18n}from'@/hooks/useI18n';import type{ObservabilityDashboardApi}from'@/api/observability/dashboard';import type{ObservabilityQueryApi}from'@/api/observability/query';import type{Dashboard,QueryItemResult}from'@/types/observability';import TimeSeriesPanel from'../components/TimeSeriesPanel.vue';import StatPanel from'../components/StatPanel.vue';import TablePanel from'../components/TablePanel.vue';import PanelState from'../components/PanelState.vue';import{computeRange,createRefreshController,groupPanelQueries}from'./dashboard-utils'
const props=defineProps<{dashboard?:Dashboard}>();const{t}=useI18n();const route=useRoute();const dashboardApi=inject<ObservabilityDashboardApi>('observabilityDashboardApi')!;const queryApi=inject<ObservabilityQueryApi>('observabilityQueryApi')!;const dashboard=ref<Dashboard|undefined>(props.dashboard),loadError=ref('');const results=ref(new Map<number,QueryItemResult>()),errors=ref(new Map<number,string>()),loading=ref(new Set<number>())
async function load(_signal:AbortSignal,_generation:number,current:()=>boolean){const value=dashboard.value;if(!value)return;const next=new Map<number,QueryItemResult>(),nextErrors=new Map<number,string>();loading.value=new Set(value.panels.map(p=>p.id));const range=computeRange(value.time_range);await Promise.all([...groupPanelQueries(value.panels)].map(async([datasource_id,queries])=>{try{const batch=await queryApi.range({datasource_id,...range,enrich_assets:false,queries},_signal);for(const item of batch.results)next.set(Number(item.ref_id.replace('panel-','')),item)}catch{for(const query of queries)nextErrors.set(Number(query.ref_id.replace('panel-','')),t('observability_ui.errors.query'))}}));if(current()){results.value=next;errors.value=nextErrors;loading.value=new Set()}}
const refresh=createRefreshController(load,()=>document.visibilityState==='hidden');let timer:number|undefined;let disposed=false
function panelState(id:number){if(loading.value.has(id))return'loading';if(errors.value.has(id))return'error';const item=results.value.get(id);if(item?.error)return'partial';if(!item?.result)return'empty';if(item.result.result_type==='string')return'unsupported';if(!item.result.scalar&&!item.result.series?.length)return'empty';return undefined}
function visibility(){refresh.setHidden(document.visibilityState==='hidden');if(document.visibilityState==='visible')void refresh.refresh()}function componentFor(type:string){return type==='stat'?StatPanel:type==='table'?TablePanel:TimeSeriesPanel}
onMounted(async()=>{try{if(!dashboard.value)dashboard.value=await dashboardApi.get(Number(route.params.id));if(disposed)return;await refresh.refresh();if(disposed)return;timer=window.setInterval(()=>void refresh.refresh(),dashboard.value.refresh_interval_s*1000);document.addEventListener('visibilitychange',visibility)}catch(error){if(!disposed)loadError.value=error instanceof Error?error.message:t('network.error')}});onBeforeUnmount(()=>{disposed=true;if(timer)clearInterval(timer);document.removeEventListener('visibilitychange',visibility);refresh.dispose()});defineExpose({dashboard,loadError,results,errors,loading,panelState,refresh})
</script>
