<template><a-form><a-input v-model:value="form.name"/><a-input v-model:value="form.description"/><a-select v-model:value="form.refresh_interval_s" :options="refreshOptions"/><a-select v-model:value="form.time_range" :options="rangeOptions"/><div v-for="(panel,index) in form.panels" :key="index"><a-select v-model:value="panel.datasource_id" :options="datasourceOptions"/><a-input v-model:value="panel.title"/><a-select v-model:value="panel.panel_type" :options="typeOptions"/><a-input v-model:value="panel.promql"/><a-select v-model:value="panel.unit" :options="unitOptions"/><a-input v-model:value="panel.legend"/><a-select v-model:value="panel.width" :options="widthOptions"/><a-button @click="move(index,-1)">Up</a-button><a-button @click="move(index,1)">Down</a-button></div><a-button @click="addPanel">Add panel</a-button><a-button :disabled="!valid" @click="save">Save</a-button></a-form></template>
<script setup lang="ts">
import{computed,inject,reactive}from'vue';import type{ObservabilityDashboardApi}from'@/api/observability/dashboard';import type{Dashboard,NamedRef,PanelInput,SaveDashboard}from'@/types/observability'
const props=defineProps<{datasources:NamedRef[];initial?:Dashboard|null}>();const emit=defineEmits<{saved:[Dashboard]}>();const api=inject<ObservabilityDashboardApi|undefined>('observabilityDashboardApi')
const form=reactive<SaveDashboard>({name:props.initial?.name??'',description:props.initial?.description??'',refresh_interval_s:props.initial?.refresh_interval_s??30,time_range:props.initial?.time_range??'1h',panels:props.initial?.panels.map(({datasource_id,title,panel_type,promql,unit,legend,sort_order,width})=>({datasource_id,title,panel_type,promql,unit,legend,sort_order,width}))??[]})
const option=<T extends string|number>(values:readonly T[])=>values.map(value=>({value,label:String(value)}));const typeOptions=option(['time_series','stat','table']as const);const unitOptions=option(['none','percent','bytes','bytes_per_second','cores','seconds','requests_per_second']as const);const widthOptions=option([6,12]as const);const refreshOptions=option([15,30,60,300]as const);const rangeOptions=option(['15m','1h','6h','24h','7d']as const);const datasourceOptions=computed(()=>props.datasources.map(x=>({value:x.id,label:x.name})))
function addPanel(){const panel:PanelInput={datasource_id:0,title:'Panel',panel_type:'time_series',promql:'',unit:'none',legend:'',sort_order:form.panels.length,width:12};form.panels.push(panel)}
function move(index:number,delta:number){const target=index+delta;if(target<0||target>=form.panels.length)return;const item=form.panels.splice(index,1)[0];if(item)form.panels.splice(target,0,item);form.panels.forEach((p,i)=>p.sort_order=i)}
const valid=computed(()=>!!form.name.trim()&&form.refresh_interval_s>0&&form.panels.length>0&&form.panels.every((p,i)=>p.datasource_id>0&&!!p.title.trim()&&!!p.promql.trim()&&p.sort_order===i&&['time_series','stat','table'].includes(p.panel_type)&&['none','percent','bytes','bytes_per_second','cores','seconds','requests_per_second'].includes(p.unit)&&[6,12].includes(p.width)))
async function save(){if(!valid.value||!api)throw new Error('invalid dashboard');const payload:SaveDashboard={...form,panels:form.panels.map((p,i)=>({...p,sort_order:i}))};const saved=props.initial?await api.update(props.initial.id,payload):await api.create(payload);emit('saved',saved)}
defineExpose({form,addPanel,move,valid,save})
</script>
