<template><a-card v-if="canRead"><a-button v-if="canWrite" @click="openCreate">Create</a-button><div v-if="errorMessage">{{ errorMessage }}</div><a-table :columns="columns" :data-source="table.items.value" :loading="table.loading.value" :pagination="false"><template #bodyCell="{column,record}"><template v-if="column.key==='actions'"><a v-if="canMetricRead" @click="openDetail(record)">View</a><a v-if="canWrite" @click="openEdit(record)">Edit</a><a-popconfirm v-if="canDelete" @confirm="remove(record)"><a>Delete</a></a-popconfirm></template></template></a-table><a-pagination :current="table.page.value" :page-size="table.pageSize.value" :total="table.total.value" @change="table.setPage"/><a-modal v-model:open="detailOpen" :footer="null" width="90%"><Detail v-if="detailOpen && viewing" :dashboard="viewing"/></a-modal><a-modal v-model:open="formOpen" :footer="null"><Form v-if="formOpen" :datasources="datasources" :initial="editing" @saved="saved"/></a-modal></a-card></template>
<script setup lang="ts">
import{computed,inject,onMounted,ref}from'vue';import{usePermission}from'@/hooks/usePermission';import{useTable}from'@/hooks/useTable';import type{ObservabilityDashboardApi}from'@/api/observability/dashboard';import type{ObservabilityDatasourceApi}from'@/api/observability/datasource';import type{Dashboard,NamedRef}from'@/types/observability';import Form from'./Form.vue';import Detail from'./Detail.vue'
const api=inject<ObservabilityDashboardApi>('observabilityDashboardApi')!,datasourceApi=inject<ObservabilityDatasourceApi>('observabilityDatasourceApi')!,p=usePermission();const canRead=computed(()=>p.has('observability:dashboard:read')),canWrite=computed(()=>p.has('observability:dashboard:write')),canDelete=computed(()=>p.has('observability:dashboard:delete')),canMetricRead=computed(()=>p.has('observability:metric:read')),canReadDatasources=computed(()=>p.has('observability:datasource:read')),errorMessage=ref(''),formOpen=ref(false),detailOpen=ref(false),editing=ref<Dashboard|null>(null),viewing=ref<Dashboard|null>(null),datasources=ref<NamedRef[]>([]);const columns=[{key:'name',title:'Name',dataIndex:'name'},{key:'refresh',title:'Refresh',dataIndex:'refresh_interval_s'},{key:'range',title:'Range',dataIndex:'time_range'},{key:'actions',title:'Actions'}];const text=(error:unknown)=>error instanceof Error?error.message:'network.error'
const table=useTable<Dashboard,{}>({fetcher:async({page,pageSize})=>{try{const x=await api.list({page,page_size:pageSize});errorMessage.value='';return{items:x.items,total:x.total}}catch(error){errorMessage.value=text(error);throw error}}})
async function loadDatasources(){if(!canReadDatasources.value)throw new Error('observability.datasource.read_required');const page=await datasourceApi.list({page:1,page_size:100});datasources.value=page.items.map(x=>({id:x.id,name:x.name}))}
async function openCreate(){try{editing.value=null;await loadDatasources();formOpen.value=true;errorMessage.value=''}catch(error){errorMessage.value=text(error)}}
async function openEdit(row:Dashboard){try{const[detail]=await Promise.all([api.get(row.id),loadDatasources()]);editing.value=detail;formOpen.value=true;errorMessage.value=''}catch(error){errorMessage.value=text(error)}}
async function openDetail(row:Dashboard){if(!canMetricRead.value)return;try{viewing.value=await api.get(row.id);detailOpen.value=true;errorMessage.value=''}catch(error){errorMessage.value=text(error)}}
async function saved(){formOpen.value=false;try{await table.reload()}catch{/* fetcher preserves error */}}
async function remove(row:Dashboard){try{await api.remove(row.id);await table.reload()}catch(error){errorMessage.value=text(error)}}onMounted(()=>{if(canRead.value)void table.reload().catch(()=>undefined)});defineExpose({canRead,canWrite,canDelete,canMetricRead,canReadDatasources,errorMessage,formOpen,detailOpen,editing,viewing,datasources,table,openCreate,openEdit,openDetail,saved,remove})
</script>
