<template><a-card v-if="canRead"><a-select v-model:value="builtinCode" :options="builtinOptions" @change="loadDefinition"/><a-select v-model:value="clusterID" :options="clusterOptions" allow-clear/><a-select v-model:value="selectedDatasourceID" :options="datasourceOptions"/><label><a-switch v-model:checked="enrichAssets"/> Asset enrichment</label><div v-for="variable in definition?.variables" :key="variable.name"><label>{{ variable.label }}</label><a-input v-model:value="variables[variable.name]"/></div><a-button @click="run">Run</a-button><component :is="componentFor(panel.panel_type)" v-for="panel in definition?.panels" :key="panel.ref_id" :result="results.get(panel.ref_id)?.result" :state="panelState(panel.ref_id)" :unit="panel.unit"/></a-card></template>
<script setup lang="ts">
import{computed,inject,onBeforeUnmount,onMounted,reactive,ref}from'vue';import{usePermission}from'@/hooks/usePermission';import type{ObservabilityDashboardApi}from'@/api/observability/dashboard';import type{ObservabilityDatasourceApi}from'@/api/observability/datasource';import type{ObservabilityQueryApi}from'@/api/observability/query';import type{BatchResult,BuiltinDashboard,DatasourceSummary,QueryItemResult}from'@/types/observability';import TimeSeriesPanel from'../components/TimeSeriesPanel.vue';import StatPanel from'../components/StatPanel.vue';import TablePanel from'../components/TablePanel.vue'
const dashboardApi=inject<ObservabilityDashboardApi>('observabilityDashboardApi')!,datasourceApi=inject<ObservabilityDatasourceApi>('observabilityDatasourceApi')!,queryApi=inject<ObservabilityQueryApi>('observabilityQueryApi')!,permission=usePermission();const canRead=computed(()=>permission.has('observability:metric:read'));const builtins=ref<BuiltinDashboard[]>([]),builtinCode=ref(''),definition=ref<BuiltinDashboard>(),datasources=ref<DatasourceSummary[]>([]),clusterID=ref<number>(),selectedDatasourceID=ref<number>(),enrichAssets=ref(false),variables=reactive<Record<string,string>>({}),results=ref(new Map<string,QueryItemResult>()),loading=ref(false);let controller:AbortController|undefined
const builtinOptions=computed(()=>builtins.value.map(x=>({value:x.code,label:x.title_key})));const clusterOptions=computed(()=>{const seen=new Map<number,string>();for(const x of datasources.value)if(x.cluster)seen.set(x.cluster.id,x.cluster.name);return[...seen].map(([value,label])=>({value,label}))});const filteredDatasources=computed(()=>datasources.value.filter(x=>!clusterID.value||!x.cluster||x.cluster.id===clusterID.value));const datasourceOptions=computed(()=>filteredDatasources.value.map(x=>({value:x.id,label:x.name})))
async function loadDefinition(){if(!builtinCode.value)return;definition.value=await dashboardApi.getBuiltin(builtinCode.value);for(const variable of definition.value.variables)variables[variable.name]=''}
function substitute(promql:string){let value=promql;for(const[name,replacement]of Object.entries(variables))value=value.replaceAll(`$${name}`,replacement);return value}
async function run(){if(!definition.value||!selectedDatasourceID.value)return;controller?.abort();controller=new AbortController();loading.value=true;try{const batch:BatchResult=await queryApi.instant({datasource_id:selectedDatasourceID.value,enrich_assets:enrichAssets.value,queries:definition.value.panels.map(x=>({ref_id:x.ref_id,promql:substitute(x.promql)}))},controller.signal);results.value=new Map(batch.results.map(x=>[x.ref_id,x]))}finally{loading.value=false}}
function panelState(refID:string){if(loading.value)return'loading';const item=results.value.get(refID);if(item?.error)return'partial';if(!item?.result)return'empty';if(item.result.result_type==='string')return'unsupported';if(!item.result.scalar&&!item.result.series?.length)return'empty';return undefined}function componentFor(type:string){return type==='stat'?StatPanel:type==='table'?TablePanel:TimeSeriesPanel}
onMounted(async()=>{const[defs,page]=await Promise.all([dashboardApi.listBuiltins(),datasourceApi.list({page:1,page_size:100})]);builtins.value=defs;datasources.value=page.items;if(defs[0]){builtinCode.value=defs[0].code;await loadDefinition()}});onBeforeUnmount(()=>controller?.abort());defineExpose({canRead,definition,clusterID,filteredDatasources,variables,selectedDatasourceID,enrichAssets,results,run,panelState})
</script>
