<template><a-card v-if="canRead"><div v-if="errorMessage">{{ errorMessage }}</div><a-select v-model:value="builtinCode" :options="builtinOptions" @change="loadDefinition"/><a-select v-model:value="clusterID" :options="clusterOptions" allow-clear/><a-select v-model:value="selectedDatasourceID" :options="datasourceOptions"/><label><a-switch v-model:checked="enrichAssets"/> {{ t('observability.builtin.asset_enrichment') }}</label><div v-for="variable in definition?.variables" :key="variable.name"><label>{{ title(variable.label) }}</label><a-input v-model:value="variables[variable.name]"/></div><a-button v-if="canRead" @click="run">{{ t('common.refresh') }}</a-button><section v-for="panel in definition?.panels" :key="panel.ref_id"><h3>{{title(panel.title_key)}}</h3><component :is="componentFor(panel.panel_type)" :result="results.get(panel.ref_id)?.result" :state="panelState(panel.ref_id)" :unit="panel.unit"/></section></a-card></template>
<script setup lang="ts">
import{computed,inject,onBeforeUnmount,onMounted,reactive,ref,watch}from'vue';import axios from'axios';import{useI18n as useVueI18n}from'vue-i18n';import{usePermission}from'@/hooks/usePermission';import type{ObservabilityDashboardApi}from'@/api/observability/dashboard';import type{ObservabilityQueryApi}from'@/api/observability/query';import type{BuiltinDashboard,QueryItemResult,QuerySource}from'@/types/observability';import TimeSeriesPanel from'../components/TimeSeriesPanel.vue';import StatPanel from'../components/StatPanel.vue';import TablePanel from'../components/TablePanel.vue';import{BuiltinRendererError,renderBuiltinQueries}from'./builtin-renderer'
const dashboardApi=inject<ObservabilityDashboardApi>('observabilityDashboardApi')!,queryApi=inject<ObservabilityQueryApi>('observabilityQueryApi')!,permission=usePermission(),{t,te}=useVueI18n();const title=(value:string)=>{const key=value.includes('.')?value:`observability.builtin.${value}`;return te(key)?t(key):value};const canRead=computed(()=>permission.has('observability:metric:read'));const builtins=ref<BuiltinDashboard[]>([]),builtinCode=ref(''),definition=ref<BuiltinDashboard>(),sources=ref<QuerySource[]>([]),clusterID=ref<number>(),selectedDatasourceID=ref<number>(),enrichAssets=ref(false),variables=reactive<Record<string,string>>({}),results=ref(new Map<string,QueryItemResult>()),loading=ref(false),errorMessage=ref('');let controller:AbortController|undefined,sequence=0,definitionController:AbortController|undefined,definitionSequence=0,disposed=false
const builtinOptions=computed(()=>builtins.value.map(x=>({value:x.code,label:title(x.title_key)})));const clusterOptions=computed(()=>[...new Set(sources.value.flatMap(x=>x.cluster_id?[x.cluster_id]:[]))].map(value=>({value,label:String(value)})));const filteredDatasources=computed(()=>sources.value.filter(x=>!clusterID.value||!x.cluster_id||x.cluster_id===clusterID.value));const datasourceOptions=computed(()=>filteredDatasources.value.map(x=>({value:x.id,label:x.name})))
function localized(error:unknown,fallback:string){if(error instanceof BuiltinRendererError)return t(`observability_ui.errors.renderer_${error.code}`);if(typeof error==='object'&&error&&'message_key'in error&&typeof error.message_key==='string')return t(error.message_key);return t(fallback)}
function invalidateQuery(){sequence++;controller?.abort();controller=undefined;results.value=new Map();loading.value=false}
function clearVariables(){for(const key of Object.keys(variables))delete variables[key]}
async function loadDefinition(){if(!builtinCode.value)return;const generation=++definitionSequence;definitionController?.abort();definitionController=new AbortController();invalidateQuery();definition.value=undefined;clearVariables();errorMessage.value='';try{const value=await dashboardApi.getBuiltin(builtinCode.value,definitionController.signal);if(generation!==definitionSequence||disposed)return;definition.value=value;for(const variable of value.variables)variables[variable.name]=''}catch(error){if(generation!==definitionSequence||disposed||axios.isCancel(error))return;errorMessage.value=localized(error,'observability.errors.load')}}
async function run(){if(!definition.value||!selectedDatasourceID.value)return;const generation=++sequence;controller?.abort();controller=new AbortController();loading.value=true;errorMessage.value='';try{const queries=renderBuiltinQueries(definition.value,variables);const batch=await queryApi.instant({datasource_id:selectedDatasourceID.value,enrich_assets:enrichAssets.value,queries},controller.signal);if(generation===sequence&&!disposed)results.value=new Map(batch.results.map(x=>[x.ref_id,x]))}catch(error){if(generation===sequence&&!disposed&&!axios.isCancel(error))errorMessage.value=localized(error,'observability.errors.query')}finally{if(generation===sequence&&!disposed)loading.value=false}}
function panelState(refID:string){if(loading.value)return'loading';if(errorMessage.value)return'error';const item=results.value.get(refID);if(item?.error)return'partial';if(!item?.result)return'empty';if(item.result.result_type==='string')return'unsupported';if(!item.result.scalar&&!item.result.series?.length)return'empty';return undefined}function componentFor(type:string){return type==='stat'?StatPanel:type==='table'?TablePanel:TimeSeriesPanel}
watch(clusterID,()=>{if(selectedDatasourceID.value&&!filteredDatasources.value.some(x=>x.id===selectedDatasourceID.value)){selectedDatasourceID.value=undefined;invalidateQuery()}})
onMounted(async()=>{if(!canRead.value)return;try{const[defs,querySources]=await Promise.all([dashboardApi.listBuiltins(),queryApi.sources()]);if(disposed)return;builtins.value=defs;sources.value=querySources;if(defs[0]){builtinCode.value=defs[0].code;await loadDefinition()}}catch(error){if(!disposed&&!axios.isCancel(error))errorMessage.value=localized(error,'observability.errors.load')}});onBeforeUnmount(()=>{disposed=true;invalidateQuery();definitionSequence++;definitionController?.abort()});defineExpose({canRead,definition,builtinCode,loadDefinition,clusterID,filteredDatasources,variables,selectedDatasourceID,enrichAssets,results,loading,errorMessage,run,panelState})
</script>
